apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: eribyteofficial/ericrypt
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name:  ${SECRET_NAME}
                  key: ENCRYPTION_KEY
            - name: ENDPOINT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  ${SECRET_NAME}
                  key: ENDPOINT_PASSWORD
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  type: ClusterIP
  clusterIP: ${ip}
  selector:
    app: ${APPLICATION_NAME}
  externalIPs:
    - 10.111.131.216
  ports:
  - targetPort: 5000
    port: 5000
    
